# Site settings
title: Bill Talkington
# email: your-email@domain.com
description: The personal site of Bill Talkington. My thoughts and projects as I explore web development and the rest of the world.
url: "http://billtalkington.github.io" # the base hostname & protocol for your site
twitter_username: BillTalkington
github_username:  BillTalkington

# Build settings
markdown: kramdown

